### ISSUE TITLE
ポインタ方向をランダムに変更する命令の実装

### ISSUE THREAD

**Issue by jpnykw** [jpnykw/befunge-interpreter#20]
https://github.com/jpnykw/befunge-interpreter/blob/fefb3dbea73a9530782a6961acf9615f18ccbb52/src/exec.rs#L89

## 仕様
ポインタの方向をランダムに変更する（上下左右のいずれか）

**Comment by jpnykw** [comment]
@azenntoyuchi TIA :eyes:

**Comment by azenntoyuchi** [comment]
今日の夜やってみますー

**Comment by azenntoyuchi** [comment]
ABC終わった後
