### ISSUE TITLE
オプション甩Componentの修正

### ISSUE THREAD

**Issue by jpnykw** [jpnykw/befunge-interpreter#39]
https://github.com/jpnykw/befunge-interpreter/commit/29571c781bc281890f2e0e23351837e5733fcdac

チェックボックスを中央に持ってきたい

**Comment by azenntoyuchi** [comment]
ListItemの
widthをfit-contentにして
margin:0 auto;を追記すると良い感じです（discordの再掲）

**Comment by jpnykw** [comment]
@azenntoyuchi ありがとうございます。こちらのCSSをもとに修正しました！

https://github.com/jpnykw/befunge-interpreter/commit/df8d374769542e0d417ea61b183a5ce6bd3c9b79
